import { StyleSheet } from 'react-native';
import { ONBOARDING_SURFACE, ONBOARDING_CTA } from './onboardingTheme';
import { sf } from '../utils/responsive';

export const ONBOARDING_AUTH_COLORS = {
  title: '#ffffff',
  subtitle: 'rgba(255, 255, 255, 0.65)',
  tertiary: 'rgba(255, 255, 255, 0.5)',
  inputText: '#ffffff',
  placeholder: 'rgba(255, 255, 255, 0.4)',
  icon: 'rgba(255, 255, 255, 0.65)',
  divider: 'rgba(255, 255, 255, 0.12)',
  link: 'rgba(255, 255, 255, 0.55)',
  linkBold: '#ffffff',
} as const;

export const onboardingAuthStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  containerPadded: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingTop: 60,
  },
  keyboardView: {
    flex: 1,
  },
  backButton: {
    position: 'absolute',
    top: 60,
    left: 20,
    zIndex: 10,
    padding: 4,
  },
  backButtonCompact: {
    position: 'absolute',
    top: 16,
    left: 20,
    zIndex: 10,
    padding: 4,
  },
  backArrowCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 120,
  },
  contentCompact: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 60,
  },
  contentCentered: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: sf(32),
    fontWeight: '600',
    color: ONBOARDING_AUTH_COLORS.title,
    marginBottom: 12,
    letterSpacing: -0.6,
  },
  titleCentered: {
    fontSize: sf(32),
    fontWeight: '600',
    color: ONBOARDING_AUTH_COLORS.title,
    marginBottom: 10,
    textAlign: 'center',
    letterSpacing: -0.6,
  },
  subtitle: {
    fontSize: sf(15),
    color: ONBOARDING_AUTH_COLORS.subtitle,
    marginBottom: 32,
  },
  subtitleCentered: {
    fontSize: sf(15),
    color: ONBOARDING_AUTH_COLORS.subtitle,
    marginBottom: 28,
    textAlign: 'center',
    lineHeight: 22,
  },
  input: {
    width: '100%',
    backgroundColor: ONBOARDING_SURFACE.fillElevated,
    borderWidth: 1,
    borderColor: ONBOARDING_SURFACE.border,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    fontSize: 16,
    color: ONBOARDING_AUTH_COLORS.inputText,
  },
  passwordContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  passwordInput: {
    width: '100%',
    backgroundColor: ONBOARDING_SURFACE.fillElevated,
    borderWidth: 1,
    borderColor: ONBOARDING_SURFACE.border,
    borderRadius: 12,
    padding: 16,
    paddingRight: 50,
    fontSize: 16,
    color: ONBOARDING_AUTH_COLORS.inputText,
  },
  eyeButton: {
    position: 'absolute',
    right: 16,
    top: 16,
    padding: 4,
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ONBOARDING_SURFACE.fillElevated,
    borderRadius: 12,
    padding: 14,
    gap: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: ONBOARDING_SURFACE.border,
  },
  socialButtonText: {
    color: ONBOARDING_AUTH_COLORS.title,
    fontSize: sf(16),
    fontWeight: '600',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: ONBOARDING_AUTH_COLORS.divider,
  },
  dividerText: {
    color: ONBOARDING_AUTH_COLORS.tertiary,
    paddingHorizontal: 16,
    fontSize: 14,
  },
  linkText: {
    color: ONBOARDING_AUTH_COLORS.link,
    fontSize: 14,
  },
  linkTextBold: {
    color: ONBOARDING_AUTH_COLORS.linkBold,
    fontWeight: '600',
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: ONBOARDING_SURFACE.fillElevated,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: ONBOARDING_SURFACE.border,
  },
  secondaryButtonText: {
    color: ONBOARDING_AUTH_COLORS.icon,
    fontSize: 15,
    fontWeight: '600',
  },
  bottomContainer: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  continueButton: {
    backgroundColor: ONBOARDING_CTA.background,
    borderRadius: ONBOARDING_CTA.borderRadius,
    paddingVertical: ONBOARDING_CTA.paddingVertical,
    alignItems: 'center',
    shadowColor: ONBOARDING_CTA.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  continueButtonDisabled: {
    opacity: 0.5,
  },
  continueButtonText: {
    color: ONBOARDING_CTA.text,
    fontSize: sf(17),
    fontWeight: '600',
    letterSpacing: 0.2,
  },
});
