import { StyleSheet, Platform } from 'react-native';
import { ONBOARDING_SURFACE, ONBOARDING_CTA, ONBOARDING_TEXT } from './onboardingTheme';
import { sf } from '../utils/responsive';

/** Shared light-theme auth/onboarding form colors. */
export const ONBOARDING_AUTH_COLORS = {
  title: ONBOARDING_TEXT.primary,
  subtitle: ONBOARDING_TEXT.body,
  tertiary: ONBOARDING_TEXT.secondary,
  inputText: ONBOARDING_TEXT.primary,
  placeholder: '#9b9bbb',
  icon: ONBOARDING_TEXT.secondary,
  divider: 'rgba(200, 185, 255, 0.35)',
  link: ONBOARDING_TEXT.secondary,
  linkBold: ONBOARDING_TEXT.primary,
} as const;

export const onboardingAuthStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  containerPadded: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingTop: 60,
  },
  keyboardView: {
    flex: 1,
  },
  backButton: {
    position: 'absolute',
    top: 60,
    left: 20,
    zIndex: 10,
    padding: 4,
  },
  backButtonCompact: {
    position: 'absolute',
    top: 16,
    left: 20,
    zIndex: 10,
    padding: 4,
  },
  backArrowCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(200, 185, 255, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 120,
  },
  contentCompact: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 60,
  },
  contentCentered: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: sf(32),
    fontWeight: '600',
    color: ONBOARDING_AUTH_COLORS.title,
    marginBottom: 12,
    letterSpacing: -1.28,
  },
  titleCentered: {
    fontSize: sf(32),
    fontWeight: '600',
    color: ONBOARDING_AUTH_COLORS.title,
    marginBottom: 10,
    textAlign: 'center',
    letterSpacing: -1.28,
  },
  subtitle: {
    fontSize: sf(15),
    color: ONBOARDING_AUTH_COLORS.subtitle,
    marginBottom: 32,
  },
  subtitleCentered: {
    fontSize: sf(15),
    color: ONBOARDING_AUTH_COLORS.subtitle,
    marginBottom: 28,
    textAlign: 'center',
    lineHeight: 22,
  },
  input: {
    width: '100%',
    height: 52,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderWidth: 1,
    borderColor: 'rgba(200, 185, 255, 0.4)',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 0,
    marginBottom: 16,
    fontSize: 16,
    lineHeight: 20,
    color: ONBOARDING_AUTH_COLORS.inputText,
    ...(Platform.OS === 'android' ? { textAlignVertical: 'center' as const } : {}),
  },
  passwordContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  passwordInput: {
    width: '100%',
    height: 52,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderWidth: 1,
    borderColor: 'rgba(200, 185, 255, 0.4)',
    borderRadius: 14,
    paddingLeft: 16,
    paddingRight: 50,
    paddingVertical: 0,
    fontSize: 16,
    lineHeight: 20,
    color: ONBOARDING_AUTH_COLORS.inputText,
    ...(Platform.OS === 'android' ? { textAlignVertical: 'center' as const } : {}),
  },
  eyeButton: {
    position: 'absolute',
    right: 12,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ONBOARDING_SURFACE.fillElevated,
    borderRadius: 14,
    padding: 14,
    gap: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: ONBOARDING_SURFACE.border,
  },
  socialButtonText: {
    color: ONBOARDING_AUTH_COLORS.title,
    fontSize: sf(16),
    fontWeight: '600',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: ONBOARDING_AUTH_COLORS.divider,
  },
  dividerText: {
    color: ONBOARDING_AUTH_COLORS.tertiary,
    paddingHorizontal: 16,
    fontSize: 14,
  },
  linkText: {
    color: ONBOARDING_AUTH_COLORS.link,
    fontSize: 14,
  },
  linkTextBold: {
    color: ONBOARDING_AUTH_COLORS.linkBold,
    fontWeight: '600',
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: ONBOARDING_SURFACE.fillElevated,
    borderRadius: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: ONBOARDING_SURFACE.border,
  },
  secondaryButtonText: {
    color: ONBOARDING_AUTH_COLORS.icon,
    fontSize: 15,
    fontWeight: '600',
  },
  bottomContainer: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  continueButton: {
    backgroundColor: ONBOARDING_CTA.background,
    borderRadius: ONBOARDING_CTA.borderRadius,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(123, 94, 167, 0.35)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 8,
  },
  continueButtonDisabled: {
    opacity: 0.5,
  },
  continueButtonText: {
    color: ONBOARDING_CTA.text,
    fontSize: sf(17),
    fontWeight: '600',
    letterSpacing: 0.2,
  },
});
